<a href="https://colab.research.google.com/github/nisaac21/TensorFlow/blob/main/Understanding_Tensors_Research.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


##**Tensors**
* What are they?
  * Vectors generalized to higher dimensions 
    * Vectors are kind of like data points, that are not bound to specific coordinates.
    * Vectors can come in any amount of dimensions
  * "A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes"
* How are they used?
  * Tensors are the main objects used in TensorFlow
  * Tensors store partially defined computation in the graph 

* Each tensor as a *datatype* (float32, int32, string, etc.) and *shape* (dimensions)

##**Creating Tensors**

In [ ]:
# tf.Variable( variable, tf.datatype)

# stores one string, of data type string
string = tf.Variable("this is a string", tf.string) 

number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float32)

# All these have a shape of one

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>

These are *scalars* - have one vlaue

Don't typically use these in programs

##**Rank/Degree of Tensors**

This is just the number of dimensions involved in the tensors.

* rank 0 = scalar
  * We don't have dimensions, its just one value 
* rank 1 = array
  * It's just one dimension, with all value stored on the same array
* rank 2 = array within array AKA matrix
* rank n = check how deeply nested lowest level array is, that is your n

Let's look at a higher level

In [ ]:
rank1_tensor = tf.Variable(["This", "is", "rank 1"], tf.string) # still a string
rank2_tensor = tf.Variable([["This is"], ["rank 2"]], tf.string)

To determine the rank of a tensors..

In [ ]:
tf.rank(rank2_tensor) #numpy is our rank

<tf.Tensor: shape=(), dtype=int32, numpy=2>

##**Shape of Tensors**

This tells us how many elements exist in each dimensions. Shape can sometimes be unknown

In [ ]:
rank2_tensor.shape 
# 2 lists in first dimension, 1 element in ea list 

TensorShape([2, 1])

##Changing Shape

We often have to do this with TensorFlow

There are many different way to reshape the data. Example, we could take our rank2, and FLATTEN it into a rank 1

In [ ]:
tensor1 = tf.ones([1,2,3]) # creates a shape of 1,2,3 filled with 1's
# 3rd dimension has two lists each of which has 3 elements of 1's in it
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [ ]:
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshapes existing data into (2,3,1)

tensor3 = tf.reshape(tensor2, [3,-1]) # -1 tells tf to calculate size
                                      # of dimension in that place 

In [ ]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


Up to here we have only used *tf.Variable* but in practice we won't use that too much. Let's look at the other types of tensors...

##**Types of Tensors**

The most commonly used tensors are...

* Variable
* Constant
* Placeholder
* SpareseTensor

Besides `Variable` all of these tensors are immuttable (value does not change during execution). 
  * All of these have constant values, whereas Variable allows for it to change 
  

##**Evaluating Tensors**

There will be times we have a tensor object, and we have to evaluate how it does something else. We use...

```python 
with tf.Session() as sess: # Uses session as default graph
  tensor.eval() # tensor would be tensor being evaluated
```